config/routes.rb
Max::Application.routes.draw do
  devise_for :users

  root :to => 'posts#index'
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
    validates_uniqueness_of :title
    def to_param
      [id, title.parameterize].join("-")
    end
  attr_accessible :description, :title, :image, :draft
 
  validates :user_id, presence: true
  validates :description, presence: true
   
  belongs_to :user
  has_attached_file :image
  
  scope :draft, -> { where(draft: true) }
  scope :published, -> { where(draft: false) }
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:per_page => 3, :page => params[:page]).order('id DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = current_user.posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
        @post = current_user.posts.new(params[:post])
    
    respond_to do |format|
      if @post.save 
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/Users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= @title %> Maximum Beta from Tony Albanese</title>
  	<link rel="stylesheet" href="stylesheet.css" type="text/css" charset="utf-8" />
	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28225535-3']);
  _gaq.push(['_setDomainName', 'maximumbeta.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  
  </head>

  <body>
    
      
  

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_footer.html.erb
<div style="background: #2c1819">
  <div class="row">
    <div class="large-6 columns">

    </div>
    <div class="large-6 columns">
      <small><p style="color: white; float: right; padding-left: 10px">Maximum Beta Copyright 2012-2013</p></small>
       <small>
          <p style="color: white; float: right;">
           <% if user_signed_in? %>
            <%= link_to 'New Post', new_post_path %>  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          <% end %>
          </p>
         </small>
    </div>
    
    </div>
    </div>
  </div> 
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div>
    <%= f.input :image, label: "Upload an Image" %>
  </div>
  
  <br>

    <div class="large-3 columns">
    <%= f.select :draft, [['Save as Draft', true], ['Publish Post', false]] %>
  </div>
    
  <div class="actions">
    <p><%= f.submit "Submit" %></p>
  </div>
<% end %>

app/views/posts/_header.html.erb
<div>
  <div class="row">
     <div style="margin-top: 15px; margin-left: 2px; margin-right: 2px"><a href="http://www.maximumbeta.com"><%= image_tag("mblogobeta.png") %></a></div>
      
  </div> 
</div>

app/views/posts/edit.html.erb
<div class="row">
    <div class="large-12 columns">
  <h2 style="color: #c37c7c !important">Edit Post</h2>
  
  <%= render 'form' %>
  
  
  <div style="float: right">
  <%= link_to 'Back', @post, class: "button" %>
  </div>
  
  <div><p>Image URL: <%=  Paperclip::Attachment.default_options[:url] %></div>
  

  
    </div>
  </div>
  

app/views/posts/index.html.erb
<%= render 'header' %><br>

<div class="row hide-for-small" style="margin-bottom: 10px"><%= image_tag("bridge.jpg") %></div>

<div class="row">
  <div class="large-4 push-8 columns">
    <p style="padding-top: 20px; text-align: center"><%= image_tag("hero.jpg") %></p>
    <h6 style="text-align: center; color: #363333">Tony Albanese | Writer & Marketer</h6>
    <p style="text-align: center">"This is a place for business & giggles."</p>

      <p style="text-align: center"><a class="button" href="mailto:albanesetr@gmail.com">Email Tony!</a> <br> Or connect using <a style="color: #c37c7c" href="http://www.twitter.com/#!/albanesetr">Twitter</a> and <a style="color: #c37c7c" href="http://www.linkedin.com/in/albanesetr">LinkedIn</a></p>
  </div>
  
  
  <div class="large-8 pull-4 columns">


        <% @posts.each do |post| %>

             
              <% if user_signed_in? %>
                  <% if post.draft == true %>
                    <h6 style="float: left; padding-right: 10px; padding-left: 10px; color: red; margin-right: 10px" class="panel">DRAFT</h6><h1 style="font-family: latohairline"><%= link_to post.title, post %></h1>
                    <p style="margin-top: -20px"></p><br>
                    <p><%= post.description.html_safe %></p>
                    <div><p><small><%= link_to 'Edit', edit_post_path(post) %> |
                    <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></small></p></div>
                    <hr>
                   
                  <% else %>
                    <h1 style="font-family: latohairline"><%= link_to post.title, post %></h1>
                    <p style="margin-top: -20px"></p><br>
                    <p><%= post.description.html_safe %></p>
                    <div><p><small><%= link_to 'Edit', edit_post_path(post) %> |
                    <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></small></p></div>
                     <hr>
                    <% end %>
              <% else %>
                  <% if post.draft == false %>
                    <h1 style="font-family: latohairline"><%= link_to post.title, post %></h1>
                    <p style="margin-top: -20px"></p><br>
                    <p><%= post.description.html_safe %></p>
                    <hr>
                  <% end %>
              <% end %>


        <% end %>
        <div style="float: right">
          <ul class="pagination">
        <%= will_paginate @posts %></ul></div>
  </div>
  
</div>

<br />

<%= render 'footer' %>

app/views/posts/new.html.erb
<% if user_signed_in? %>
  
  <div class="row">
    <div class="large-12 columns">
  <h2 style="color: #c37c7c !important">New Post</h2>
  
  <%= render 'form' %>
  
  <%= link_to 'Nevermind', posts_path, class: "button" %>
  
    </div>
  </div>
  
  
  
<% else %>
  
  <div class="panel"><h2>Sorry you must be logged in to create a new post!</h2>
    <p>Please contact Tony Albanese if you would like to contribute to Maximum Beta, <a href="mailto:albanesetr@gmail.com">albanesetr@gmail.com</a>.</p>
    <p>Or continue reading the <a href="http://www.maximumbeta.com">blog</a>.</p>
  
  </div>
  
<% end %>

app/views/posts/show.html.erb
<% @title= @post.title %>

<p id="notice"><%= notice %></p>
<%= render 'header' %><br>

<div class=row>
  <div class="large-12 columns">
    <h1 class="custom_font" style="color: #c37c7c; text-align: center; font-family: latohairline"><%= @post.title %></h1>
    <p style="margin-top: -25px; text-align: center"></p>
    <br>
  <hr>
    
  <p>
    <%= @post.description.html_safe %>
  </p>
  
   <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'maximumbeta'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    
  
  <p style="text-align: center"><%= link_to 'View All Posts', posts_path, class: "button" %></p>
    </div>
  
  <% if user_signed_in? %>
              <div><p><small><%= link_to 'Edit Post', edit_post_path %></small>
            <% else %>
          <% end %>
          
</div>

<br />

<%= render 'footer' %>